# Base workflow for building out tool with cmake on various operating systems

name: Kami CICD pipeline with CMake

on:
  pull_request:
    branches: [ main ]

jobs:
  build_and_run_kami:

    runs-on: ubuntu-latest

    steps:
      - name: Cloning repository
        uses: actions/checkout@v4

      - name: Creating build directory
        run: mkdir build

      - name: Generating makefile
        run: cmake -B ./build/ 
              -DCMAKE_CXX_COMPILER=g++
              -DCMAKE_C_COMPILER=gcc
              -DCMAKE_BUILD_TYPE=Release
              -S ./src/

      - name: Create binary
        run: cd ./build && make

      - name: Run binary
        run: ./build/kami

      - name: Cleaning up
        run: cd ./build && make clean

  build_and_run_tests:

    runs-on: ubuntu-latest

    steps:
      - name: Cloning repository
        uses: actions/checkout@v4

      - name: Creating build directory
        run: mkdir ./test/build

      - name: Generating makefile
        run: cmake -S ./test -B ./test/build

      - name: Create testing binary
        run: cmake --build ./test/build

      - name: Run test binary
        run: ./test/build/kami_test

      - name: Cleaning up
        run: cd ./test/build && make clean
